app:
  kafka:
    topics:
      transfer-events:
        name: transfer-events
      notification-events:
        name: notification-events
        retryName: notification-events-retry
        partitions: 4
        maxAttempts: 10
        delay: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"  # ← Expõe TODOS os endpoints (dev only)

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    io.github.resilience4j: INFO