spring:
  application:
    name: demo
  main:
    banner-mode: off
  # Datasource Configuration
  datasource:
    url: jdbc:h2:mem:pay-db;INIT=CREATE SCHEMA IF NOT EXISTS app
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # H2 Console (desenvolvimento)
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  # JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 6000ms
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: simplepay-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      isolation-level: read_committed
    producer:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

kafka:
  topics:
    transfer-events: transfer-events
    notification-events: notification-events

external:
  authorization:
    url: https://util.devi.tools/api/v2
  notification:
    url: https://util.devi.tools/api/v1

management:
  endpoints:
    web:
      exposure:
        include: "*"  # ← Expõe TODOS os endpoints (dev only)
  endpoint:
    health:
      show-details: always  # ← Mostra detalhes sempre

  health:
    circuitbreakers:
      enabled: true  # ← Habilita health dos CBs


# Resilience4j - Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - com.example.demo.infra.exception.InfraException
          - org.springframework.web.client.RestClientException
        ignoreExceptions:
          - com.example.demo.domain.exception.DomainException

    instances:
      # Authorization Service - Crítico, fail-fast
      authorizationService:
        baseConfig: default
        slowCallDurationThreshold: 5s
        slowCallRateThreshold: 50

      # Notification Service - Não crítico, mais permissivo
      notificationService:
        baseConfig: default
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 70
        slowCallDurationThreshold: 10s
        slowCallRateThreshold: 70
        recordExceptions:
          - com.example.demo.infra.exception.InfraException
          - org.springframework.web.client.RestClientException
          - com.example.demo.application.exceptions.NotificationException
