spring:
  jpa:
    show-sql: true

app:
  kafka:
    topics:
      notification-requested:
        name: notification-requested
        partitions: 4
        maxAttempts: 2
        delay: 5000
      notification-sent:
        name: notification-sent
        partitions: 4

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.lang.Exception

    #        ignoreExceptions:
    #          - com.example.demo.domain.exception.FieldValidationException

    instances:
      # Authorization Service - Mais restritivo (crítico)
      authorizationService:
        baseConfig: default
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50  # 50% de falhas abre o circuito
        slowCallDurationThreshold: 5s
        slowCallRateThreshold: 50

      # Notification Service - Mais permissivo (não crítico)
      notificationService:
        baseConfig: default
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 15s
        failureRateThreshold: 70  # 70% de falhas abre o circuito
        slowCallDurationThreshold: 10s
        slowCallRateThreshold: 70

management:
  endpoints:
    web:
      exposure:
        include: "*"  # ← Expõe TODOS os endpoints (dev only)

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
    org.springframework.web: DEBUG
    io.github.resilience4j: DEBUG
    org.hibernate.SQL: ERROR
    org.apache.kafka.common.config: WARN